theme: jekyll-theme-giellalt
title: Dictionary for Russian ⇒ Vepsian
description: An electronic dictionary from Russian to Vepsian

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
